* Terminal
** Kitty
*** Set colors
- [[https://sw.kovidgoyal.net/kitty/conf/#color-scheme][Add colors to =kitty.conf=]]
- Add =allow_remote_control yes= to =kitty.conf=
- Run =kitty @set-colors --all --configured=

** See what is slowing down terminal startup
To see every command that runs during your shell's startup configuration, put

#+begin_example
set -x
#+end_example

at the top and

#+begin_example
set +x
#+end_example

at the bottom of both files =~/.profile= and =~/.bashrc=.

Then in a terminal, run:

#+begin_example
$ bash --login
#+end_example

and see which command takes the most time.

[[https://askubuntu.com/questions/717961/shell-very-slow-to-load-ubuntu-14-04][Source]]

** =tmux=
*** Have =tmux= start by default
#+begin_example
if [ "$TMUX" = "" ]; then tmux; fi
#+end_example

[[https://unix.stackexchange.com/questions/41274/having-tmux-load-by-default-when-a-zsh-terminal-is-launched][Source]]

*** Highlight and select text
Hold shift while selecting text

*** Highlighting across panes
- [[https://github.com/tmux/tmux/issues/2096][Issue - Copying text with panes in a vertical split #2096]]

#+begin_quote
Huh copy/paste works fine with vertical splits. Just setup tmux to sync your tmux clipboard with your regular x (or osx if you're into that kind of thing) clipboard.

You mean selecting text with a mouse on a vertical split? If so get tmux upgraded to 1.8+ then prefix-z and you can temporarily zoom the window to full screen.

Your information on tmux is highly out of date.

Also prefix-alt-2 will move to horizontal layout of panes.

#+end_quote

[[https://news.ycombinator.com/item?id=7758368][Source]]

*** Home and End keys don't work
Add to =.zshrc=:

#+begin_example
bindkey  "^[[1~"   beginning-of-line
bindkey  "^[[4~"   end-of-line
#+end_example

*** Reload config
#+begin_example
tmux source-file ~/.tmux.conf
#+end_example

*** ='xterm-new': unknown terminal type=
#+begin_example
# Run the following commands on the local machine's bash prompt
echo "export TERM=xterm-256color" >> ~/.bashrc
source ~/.bashrc
#+end_example

[[https://stackoverflow.com/questions/27052587/xterm-new-unknown-terminal-type][Source]]

*** Setting =$TERM=
When running tmux then you must use =TERM=screen=, =TERM=tmux=, or one of the derivatives e.g. =TERM=screen-256color= or TERM==tmux-256color=.

[[https://unix.stackexchange.com/questions/484775/screen-and-kitty-what-should-term-be][Source]]
