* X
** Keep xrandr/arandr settings
You will note that arandr has the option somewhere in its menu system to save your current configuration as a shell script. Do that, then append the contents of the newly written file to the end of your =~/.xinitrc=.

** Set screen timeout
You can disable the screen saver feature with:

#+begin_example
xset s off
#+end_example

The power saving feature can be turned off with

#+begin_example
xset -dpms
#+end_example

With these settings the screen should no longer turn off or blank automatically until you reboot your machine. - [[https://askubuntu.com/questions/763994/screen-times-out-in-i3-wm][Source]]

** =xmodmap: please release the following keys=
Put =xmodmap= in =.xinitrc= not =.bashrc=

[[https://unix.stackexchange.com/questions/450971/xmodmap-key-bindings-reset-when-i-open-a-new-tab-in-the-shell#516263][Source]]

** xprop
Use to find the title of the program that you can use in =i3= config, =compton= config, etc.

Run =xprop= and then click on the window you want, the title is the second string in the =WM_CLASS= line.
